from api.tests.company import CompanyListCreateAPIViewTestCase
from api.tests.pedido import PedidoUpdateAPIViewTestCase
from api.tests.tecnico import TecnicoListAPIViewTestCase, TecnicoReportAPIViewTestCase